#!/bin/sh

# Exit status used to report back to caller
#
STATUS=0

export HDF5_DISABLE_VERSION_CHECK=1

# Run the standard set of unittests
#
python -m unittest discover -q test
RESULT=$?
if [ "$RESULT" -ne "0" ]; then
    STATUS=1
    echo "ERROR: unittest generated errors"
fi



# Run pylint
#
pylint PyMods swotrepr.py --disable=E0401 --extension-pkg-whitelist=netCDF4
RESULT=$?
RESULT=$((3 & $RESULT))
if [ "$RESULT" -ne "0" ]; then
    STATUS=1
    echo "ERROR: pylint generated errors"
fi



# Run the python safety check
#
safety check
RESULT=$?
if [ "$RESULT" -ne "0" ]; then
    STATUS=1
    echo "ERROR: safety check generated errors"
fi



exit $STATUS
