#!/bin/sh

# Exit status used to report back to caller
#
STATUS=0

export HDF5_DISABLE_VERSION_CHECK=1

# Run the standard set of unittests, producing JUnit compatible output
#
coverage run -m xmlrunner discover test -o test/reports

RESULT=$?
if [ "$RESULT" -ne "0" ]; then
    STATUS=1
    echo "ERROR: unittest generated errors"
fi


echo "Test Coverage Estimates"
coverage report --omit="*test/*"
coverage html --omit="*test/*" -d /home/test/coverage


# Run pylint
#
pylint pymods swotrepr.py --disable=E0401 --extension-pkg-whitelist=netCDF4
RESULT=$?
RESULT=$((3 & $RESULT))
if [ "$RESULT" -ne "0" ]; then
    STATUS=1
    echo "ERROR: pylint generated errors"
fi



# Run the python safety check
#
# CVE issue ID 39462 is an open issue against all tornado versions (>=6.1);
# it relates to web cache poisoning. Snyk lists it as a medium vulnerability.
# There is no remediation at this point (2021-02-05).
#
safety check --ignore=39462
RESULT=$?
if [ "$RESULT" -ne "0" ]; then
    STATUS=1
    echo "ERROR: safety check generated errors"
fi



exit $STATUS
